name: Build and Release Electron App

on:
  push:
    tags: ['v*']  # 当推送 v 开头的标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # 可以添加多个平台，这里以 Windows 为例
        os: [windows-latest]
        # 如果想构建多个平台，可以取消下面的注释
        # include:
        #   - os: windows-latest
        #     artifact_name: SignalRGB-Editor-Windows
        #   - os: macos-latest
        #     artifact_name: SignalRGB-Editor-Mac
        #   - os: ubuntu-latest
        #     artifact_name: SignalRGB-Editor-Linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Electron app
      run: npm run build
      env:
        # 如果构建需要其他环境变量，可以在这里设置
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SignalRGB-Editor-${{ matrix.os }}
        path: |
          dist/*.exe
          dist/*.blockmap
          dist/latest.yml
        retention-days: 30
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.blockmap
          dist/latest.yml
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
